## Clock
set_property PACKAGE_PIN W5 [get_ports clk]
    set_property IOSTANDARD LVCMOS33 [get_ports clk]
create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports clk]

## Reset (Center Button)
set_property PACKAGE_PIN U18 [get_ports reset]
    set_property IOSTANDARD LVCMOS33 [get_ports reset]

## Mode Button (Top Button - toggles debug/run)
set_property PACKAGE_PIN T18 [get_ports btnMode]
    set_property IOSTANDARD LVCMOS33 [get_ports btnMode]

## ALU Result Button (Right Button - toggles ALU display)
set_property PACKAGE_PIN T17 [get_ports btnAlu]
    set_property IOSTANDARD LVCMOS33 [get_ports btnAlu]

## Full Reset Button (Left Button - resets everything)
set_property PACKAGE_PIN W19 [get_ports btnLeft]
    set_property IOSTANDARD LVCMOS33 [get_ports btnLeft]

## 32-bit Output Button (Down Button - toggles 32-bit program output)
set_property PACKAGE_PIN U17 [get_ports btnDown]
    set_property IOSTANDARD LVCMOS33 [get_ports btnDown]

## Switches
set_property PACKAGE_PIN V17 [get_ports {switches[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {switches[0]}]
set_property PACKAGE_PIN V16 [get_ports {switches[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {switches[1]}]
set_property PACKAGE_PIN W16 [get_ports {switches[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {switches[2]}]
set_property PACKAGE_PIN W17 [get_ports {switches[3]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {switches[3]}]
set_property PACKAGE_PIN W15 [get_ports {switches[4]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {switches[4]}]
set_property PACKAGE_PIN V15 [get_ports {switches[5]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {switches[5]}]
set_property PACKAGE_PIN W14 [get_ports {switches[6]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {switches[6]}]
set_property PACKAGE_PIN W13 [get_ports {switches[7]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {switches[7]}]
set_property PACKAGE_PIN V2  [get_ports {switches[8]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {switches[8]}]
set_property PACKAGE_PIN T3  [get_ports {switches[9]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {switches[9]}]
set_property PACKAGE_PIN T2  [get_ports {switches[10]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {switches[10]}]
set_property PACKAGE_PIN R3  [get_ports {switches[11]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {switches[11]}]
set_property PACKAGE_PIN W2  [get_ports {switches[12]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {switches[12]}]
set_property PACKAGE_PIN U1  [get_ports {switches[13]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {switches[13]}]
set_property PACKAGE_PIN T1  [get_ports {switches[14]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {switches[14]}]
set_property PACKAGE_PIN R2  [get_ports {switches[15]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {switches[15]}]

## LEDs
set_property PACKAGE_PIN U16 [get_ports {leds[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {leds[0]}]
set_property PACKAGE_PIN E19 [get_ports {leds[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {leds[1]}]
set_property PACKAGE_PIN U19 [get_ports {leds[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {leds[2]}]
set_property PACKAGE_PIN V19 [get_ports {leds[3]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {leds[3]}]
set_property PACKAGE_PIN W18 [get_ports {leds[4]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {leds[4]}]
set_property PACKAGE_PIN U15 [get_ports {leds[5]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {leds[5]}]
set_property PACKAGE_PIN U14 [get_ports {leds[6]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {leds[6]}]
set_property PACKAGE_PIN V14 [get_ports {leds[7]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {leds[7]}]
set_property PACKAGE_PIN V13 [get_ports {leds[8]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {leds[8]}]
set_property PACKAGE_PIN V3  [get_ports {leds[9]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {leds[9]}]
set_property PACKAGE_PIN W3  [get_ports {leds[10]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {leds[10]}]
set_property PACKAGE_PIN U3  [get_ports {leds[11]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {leds[11]}]
set_property PACKAGE_PIN P3  [get_ports {leds[12]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {leds[12]}]
set_property PACKAGE_PIN N3  [get_ports {leds[13]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {leds[13]}]
set_property PACKAGE_PIN P1  [get_ports {leds[14]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {leds[14]}]
set_property PACKAGE_PIN L1  [get_ports {leds[15]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {leds[15]}]

## 7-Segment Display Cathodes
set_property PACKAGE_PIN W7 [get_ports {segments[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {segments[0]}]
set_property PACKAGE_PIN W6 [get_ports {segments[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {segments[1]}]
set_property PACKAGE_PIN U8 [get_ports {segments[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {segments[2]}]
set_property PACKAGE_PIN V8 [get_ports {segments[3]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {segments[3]}]
set_property PACKAGE_PIN U5 [get_ports {segments[4]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {segments[4]}]
set_property PACKAGE_PIN V5 [get_ports {segments[5]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {segments[5]}]
set_property PACKAGE_PIN U7 [get_ports {segments[6]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {segments[6]}]

## 7-Segment Anodes
set_property PACKAGE_PIN U2 [get_ports {displayPower[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {displayPower[0]}]
set_property PACKAGE_PIN U4 [get_ports {displayPower[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {displayPower[1]}]
set_property PACKAGE_PIN V4 [get_ports {displayPower[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {displayPower[2]}]
set_property PACKAGE_PIN W4 [get_ports {displayPower[3]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {displayPower[3]}]
