webtalk_init -webtalk_dir C:/Users/rb10107/Desktop/CA_lab10/CA_Labs_MyrahHussain_RomaisaShazad/CA_Lab09_Myrah_Romaisa/All_CA_Labs.sim/sim_1/behav/xsim/xsim.dir/tb_lab10_top_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sat Apr 11 12:39:50 2026" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2902540" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "92461532-248a-4880-b6bd-21de2e541713" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "10d31688e6854bf7bbaf7dc3b0d28415" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "8" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "13th Gen Intel(R) Core(TM) i5-13500" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2496 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "0 ps" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "1.72_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "16860_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2214117744 -regid "" -xml C:/Users/rb10107/Desktop/CA_lab10/CA_Labs_MyrahHussain_RomaisaShazad/CA_Lab09_Myrah_Romaisa/All_CA_Labs.sim/sim_1/behav/xsim/xsim.dir/tb_lab10_top_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/rb10107/Desktop/CA_lab10/CA_Labs_MyrahHussain_RomaisaShazad/CA_Lab09_Myrah_Romaisa/All_CA_Labs.sim/sim_1/behav/xsim/xsim.dir/tb_lab10_top_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/rb10107/Desktop/CA_lab10/CA_Labs_MyrahHussain_RomaisaShazad/CA_Lab09_Myrah_Romaisa/All_CA_Labs.sim/sim_1/behav/xsim/xsim.dir/tb_lab10_top_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
