## Clock signal (100 MHz)
set_property PACKAGE_PIN W5 [get_ports clk]							
    set_property IOSTANDARD LVCMOS33 [get_ports clk]
    create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports clk]

## Switches
set_property PACKAGE_PIN V17 [get_ports {switches_in[0]}]					
    set_property IOSTANDARD LVCMOS33 [get_ports {switches_in[0]}]
set_property PACKAGE_PIN V16 [get_ports {switches_in[1]}]					
    set_property IOSTANDARD LVCMOS33 [get_ports {switches_in[1]}]
set_property PACKAGE_PIN W16 [get_ports {switches_in[2]}]					
    set_property IOSTANDARD LVCMOS33 [get_ports {switches_in[2]}]
set_property PACKAGE_PIN W17 [get_ports {switches_in[3]}]					
    set_property IOSTANDARD LVCMOS33 [get_ports {switches_in[3]}]
set_property PACKAGE_PIN W15 [get_ports {switches_in[4]}]					
    set_property IOSTANDARD LVCMOS33 [get_ports {switches_in[4]}]
set_property PACKAGE_PIN V15 [get_ports {switches_in[5]}]					
    set_property IOSTANDARD LVCMOS33 [get_ports {switches_in[5]}]
set_property PACKAGE_PIN W14 [get_ports {switches_in[6]}]					
    set_property IOSTANDARD LVCMOS33 [get_ports {switches_in[6]}]
set_property PACKAGE_PIN W13 [get_ports {switches_in[7]}]					
    set_property IOSTANDARD LVCMOS33 [get_ports {switches_in[7]}]
set_property PACKAGE_PIN V2 [get_ports {switches_in[8]}]					
    set_property IOSTANDARD LVCMOS33 [get_ports {switches_in[8]}]
set_property PACKAGE_PIN T3 [get_ports {switches_in[9]}]					
    set_property IOSTANDARD LVCMOS33 [get_ports {switches_in[9]}]
set_property PACKAGE_PIN T2 [get_ports {switches_in[10]}]					
    set_property IOSTANDARD LVCMOS33 [get_ports {switches_in[10]}]
set_property PACKAGE_PIN R3 [get_ports {switches_in[11]}]					
    set_property IOSTANDARD LVCMOS33 [get_ports {switches_in[11]}]
set_property PACKAGE_PIN W2 [get_ports {switches_in[12]}]					
    set_property IOSTANDARD LVCMOS33 [get_ports {switches_in[12]}]
set_property PACKAGE_PIN U1 [get_ports {switches_in[13]}]					
    set_property IOSTANDARD LVCMOS33 [get_ports {switches_in[13]}]
set_property PACKAGE_PIN T1 [get_ports {switches_in[14]}]					
    set_property IOSTANDARD LVCMOS33 [get_ports {switches_in[14]}]
set_property PACKAGE_PIN R2 [get_ports {switches_in[15]}]					
    set_property IOSTANDARD LVCMOS33 [get_ports {switches_in[15]}]
## LEDs
# Data Patterns (Bottom 8 LEDs)
set_property PACKAGE_PIN U16 [get_ports {leds_out[0]}]					
    set_property IOSTANDARD LVCMOS33 [get_ports {leds_out[0]}]
set_property PACKAGE_PIN E19 [get_ports {leds_out[1]}]					
    set_property IOSTANDARD LVCMOS33 [get_ports {leds_out[1]}]
set_property PACKAGE_PIN U19 [get_ports {leds_out[2]}]					
    set_property IOSTANDARD LVCMOS33 [get_ports {leds_out[2]}]
set_property PACKAGE_PIN V19 [get_ports {leds_out[3]}]					
    set_property IOSTANDARD LVCMOS33 [get_ports {leds_out[3]}]
set_property PACKAGE_PIN W18 [get_ports {leds_out[4]}]					
    set_property IOSTANDARD LVCMOS33 [get_ports {leds_out[4]}]
set_property PACKAGE_PIN U15 [get_ports {leds_out[5]}]					
    set_property IOSTANDARD LVCMOS33 [get_ports {leds_out[5]}]
set_property PACKAGE_PIN U14 [get_ports {leds_out[6]}]					
    set_property IOSTANDARD LVCMOS33 [get_ports {leds_out[6]}]
set_property PACKAGE_PIN V14 [get_ports {leds_out[7]}]					
    set_property IOSTANDARD LVCMOS33 [get_ports {leds_out[7]}]

# State Debug (Top 3 LEDs)
set_property PACKAGE_PIN V13 [get_ports {leds_out[8]}]					
    set_property IOSTANDARD LVCMOS33 [get_ports {leds_out[8]}]
set_property PACKAGE_PIN V3 [get_ports {leds_out[9]}]					
    set_property IOSTANDARD LVCMOS33 [get_ports {leds_out[9]}]
set_property PACKAGE_PIN W3 [get_ports {leds_out[10]}]					
    set_property IOSTANDARD LVCMOS33 [get_ports {leds_out[10]}]
set_property PACKAGE_PIN U3 [get_ports {leds_out[11]}]					
    set_property IOSTANDARD LVCMOS33 [get_ports {leds_out[11]}]
set_property PACKAGE_PIN P3 [get_ports {leds_out[12]}]					
    set_property IOSTANDARD LVCMOS33 [get_ports {leds_out[12]}]
set_property PACKAGE_PIN N3 [get_ports {leds_out[13]}]					
    set_property IOSTANDARD LVCMOS33 [get_ports {leds_out[13]}]
set_property PACKAGE_PIN P1 [get_ports {leds_out[14]}]					
    set_property IOSTANDARD LVCMOS33 [get_ports {leds_out[14]}]
set_property PACKAGE_PIN L1 [get_ports {leds_out[15]}]					
    set_property IOSTANDARD LVCMOS33 [get_ports {leds_out[15]}]
## Buttons
# Center Button for Reset
set_property PACKAGE_PIN U18 [get_ports rst]						
    set_property IOSTANDARD LVCMOS33 [get_ports rst]
# Top Button for Start
set_property PACKAGE_PIN T18 [get_ports start]						
    set_property IOSTANDARD LVCMOS33 [get_ports start]
